---

virtualenv_path: "/home/ubuntu/.virtualenvs/blog_analytics"
git_repo: https://github.com/yeti/rocketu_blog_analytics.git
project_name: rocketu_blog_analytics
project_path: "/home/ubuntu/{{ project_name }}"
requirements_file: "{{ project_path }}/requirements.txt"